version: '3'

services:
  # Serviço que irá rodar o backend
  node:
    image: node:16.14
    container_name: backend
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm run debug"
    restart: always
    working_dir: /home/node/app/backend
    volumes:
      - ./:/home/node/app/
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database # Nome do service que será utilizado para o banco de dados
      PORT: 3001

 # Serviço que irá rodar o frontend
  frontend:
    image: node:16.14
    container_name: frontend
    tty: true
    stdin_open: true
    restart: always
    working_dir: /home/node/app/frontend
    volumes:
      - ./frontend:/home/node/app/frontend
    ports:
      - 80:3000 # Redirecionar a porta 3000 do Node.js para a porta 80 no host
    command: bash -c "npm install && npm start"

  # Serviço rodando o banco de dados
  database:
    image: mysql:8.0.29
    container_name: todolist_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolistdb
    ports:
      - 33060:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d